name: GitHub Actions CI/CD

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ build-essential libopenmpi-dev python3 python3-pip libboost-json-dev
        pip install mpi4py
        sudo chmod +x example_controller_2.py

    - name: Run tests
      run: |
        make test
